- block:
  - name: Update apt sources for latest nodejs
    ansible.builtin.shell: curl -fsSL https://deb.nodesource.com/setup_current.x | bash -

  - name: Install nodejs and npm for Debian
    ansible.builtin.apt:
      name:
        - nodejs
        - npm
      state: present
      update_cache: yes
      cache_valid_time: 0

  become: yes
  become_user: root
  become_method: sudo
  ignore_errors: true
  when: ansible_facts['os_family']|lower == 'debian'

- name: Install nodejs for RHEL
  ansible.builtin.shell: curl -fsSL https://rpm.nodesource.com/setup_current.x | bash -
  become: yes
  become_user: root
  become_method: sudo
  ignore_errors: true
  when: ansible_facts['os_family']|lower == 'redhat'

- name: Install nodejs for macOS
  community.general.homebrew: name=node state=present
  when: ansible_facts['os_family']|lower == 'darwin'
