- import_tasks: install.yaml
- import_tasks: create_local_dirs.yaml

- name: "{{ dotfile_action|capitalize }} nodejs configuration"
  ansible.builtin.include_tasks: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "config_{{ dotfile_action|lower }}.yaml"
      paths:
        - 'tasks'
  ignore_errors: true 

- name: Install npm packages
  community.general.npm:
    name: '{{ item }}'
    path: '{{ user_home_folder }}/.npm_packages'
    state: latest
  loop:
    - typescript
    - javascript-typescript-langserver
