- include_tasks: config_uninstall.yaml

- name: Check if zsh configuration exists
  ansible.builtin.stat: path="{{ zsh_config_path }}"
  register: zsh_conf_stat


- name: Back up existing zsh configuration
  ansible.builtin.command: "mv {{ zsh_conf_stat.stat.path }} {{ zsh_conf_stat.stat.path + '.old' }}"
  args:
    creates: "{{ zsh_conf_stat.stat.path + '.old' }}"
  when: zsh_conf_stat.stat.exists


- name: Stow zsh configuration
  stow: 
    package: payload
    dir: "{{ role_path }}"
    target: "{{ user_home_folder }}"
    state: present

