- name: Ensure gdb is available on the host
  block:
    - name: Check if gdb command is available
      shell: command -v gdb &> /dev/null
      register: gdb_command_exist

    - name: Stop configuration if gdb command do not exist
      fail:
        msg: "Stopping configuration as gdb command is not found."
      when: gdb_command_exist.rc != 0

- name: "{{ dotfile_action|capitalize }} gdb configuration"
  ansible.builtin.include_tasks: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "config_{{ dotfile_action|lower }}.yaml"
      paths:
        - 'tasks'
  ignore_errors: true
